### ISSUE TITLE
Confused about the folder structure.

### ISSUE THREAD

**Issue by chrislaurie-io** [kauemurakami/getx_pattern#17]
I am investigating Get as the core approach to our new application. It seems there are a few different folder structure.

getx_cli init creates a folder structure - this has no UI folder

The current Getx pattern info page (https://kauemurakami.github.io/getx_pattern/#home) does refer to a ui folder

GetX snippets has another structure on its details page. It says: Proposed structure -> subsequent changes will not change the current structure. This adds a core folder with them & utils subfolders and a module's structure looks different.

There is also GitHub issue in this repository with yet another proposed layout. 

The examples in this repository has another structure. This has an android folder buried in the UI folder which is a bt confusing.

I suspect it does not matter, except for the assumptions the VS plugin makes about what lives where.

**Comment by kauemurakami** [comment]
Sim, na documentação/site temos duas versões, mas a do readme e a mais atualizada.
São variados exemplos, com o tempo a própria estrutura mudou, evoluiu, então pode haver pontos deixados para trás.
A abordagem da paste UI com android e ios é apenas na estrutura de módulos, pois pessoas me pediram por isso também aqui nas issues, mesmo não estando no exemplo ou sendo sempre implementada pois não é muito comum pra uma arquitetura genérica.
Atente-se ao readme deste repositório.

**Comment by kauemurakami** [comment]
Yes, in the Documents / website we have two versions, but the readme and the most updated.
There are several examples, over time the structure itself has changed, evolved, so there may be points left behind.
The approach to paste UI with android and ios is only in the module structure, because people asked me for it here also in the questions, even if not used in the example or always being implemented because it is not very common for a generic architecture.
About the cli, I am not the same maintainer of the package, it may be out of date.
About the architecture I recommend using it in modules
Pay attention to the readme of this repository.
