### ISSUE TITLE
Why is there only Android configuration under UI, IOS configuration? I don't think it makes a lot of sense

### ISSUE THREAD

**Issue by lgengsy** [kauemurakami/getx_pattern#29]
app -  ui - android

**Comment by kauemurakami** [comment]
Because it is extremely intuitive, and if you were writing it would be very extensive, in addition to the package structure being deprecated, I recommend that you see the section on github's readme or the initial modular version on the site.
But read android, tv, smart watch, ios, desktop, linux, web, among the other UI's that flutter can be applied to.
